# Variables
@baseUrl = http://localhost:3333

# Get rooms
GET {{baseUrl}}/rooms

###

# Create room
POST {{baseUrl}}/rooms
Content-Type: application/json

{
  "name": "testing room",
  "description": "testing room description"
}
