# Variables
@baseUrl = http://localhost:3333

# Get rooms
GET {{baseUrl}}/rooms

###

# Create room
# @name createRoom
POST {{baseUrl}}/rooms
Content-Type: application/json

{
  "name": "testing room",
  "description": "testing room description"
}

###
@roomId = {{createRoom.response.body.$.roomId}}

###

# Get questions
GET {{baseUrl}}/room/{{roomId}}/questions

###

# Create question
POST {{baseUrl}}/room/{{roomId}}/questions
Content-Type: application/json

{
  "question": "testing question"
}
